# .readthedocs.yaml
version: 2

submodules:
  include: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools: { python: "3.10" }
  apt_packages:
    - mpich
    - cmake
    - libhdf5-mpi-dev
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - uv sync --extra docs
      - source .venv/bin/activate

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  #fail_on_warning: true
