version: '2'
services:
  miv_simulator:
    image: miv_env:0.1
    ports:
      - "8888:8888"
    volumes:
      - .:/home/user/MiV-Simulator
    command:
      - jupyter
      - lab
      - --app_dir=/home/user
      - --port=8888
      - --allow-root
      - --ip=0.0.0.0
      - --NotebookApp.token=''
      - --NotebookApp.password=''
